Project/unops3/src/java/unops34/EstadoController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unops34;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.List;
import javax.faces.FacesException;
import javax.annotation.Resource;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.model.SelectItem;
import javax.persistence.EntityManagerFactory;
import javax.persistence.PersistenceUnit;
import javax.transaction.UserTransaction;
import unops34.util.JsfUtil;
import unops34.util.PagingInfo;

/**
 *
 * @author Dell
 */
public class EstadoController {

    public EstadoController() {
        pagingInfo = new PagingInfo();
        converter = new EstadoConverter();
    }
    private Estado estado = null;
    private List<Estado> estadoItems = null;
    private EstadoFacade jpaController = null;
    private EstadoConverter converter = null;
    private PagingInfo pagingInfo = null;
    @Resource
    private UserTransaction utx = null;
    @PersistenceUnit(unitName = "unops3PU")
    private EntityManagerFactory emf = null;

    public PagingInfo getPagingInfo() {
        if (pagingInfo.getItemCount() == -1) {
            pagingInfo.setItemCount(getJpaController().count());
        }
        return pagingInfo;
    }

    public EstadoFacade getJpaController() {
        if (jpaController == null) {
            FacesContext facesContext = FacesContext.getCurrentInstance();
            jpaController = (EstadoFacade) facesContext.getApplication().getELResolver().getValue(facesContext.getELContext(), null, "estadoJpa");
        }
        return jpaController;
    }

    public SelectItem[] getEstadoItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(getJpaController().findAll(), false);
    }

    public SelectItem[] getEstadoItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(getJpaController().findAll(), true);
    }

    public Estado getEstado() {
        if (estado == null) {
            estado = (Estado) JsfUtil.getObjectFromRequestParameter("jsfcrud.currentEstado", converter, null);
        }
        if (estado == null) {
            estado = new Estado();
        }
        return estado;
    }

    public String listSetup() {
        reset(true);
        return "estado_list";
    }

    public String createSetup() {
        reset(false);
        estado = new Estado();
        return "estado_create";
    }

    public String create() {
        try {
            utx.begin();
        } catch (Exception ex) {
        }
        try {
            Exception transactionException = null;
            getJpaController().create(estado);
            try {
                utx.commit();
            } catch (javax.transaction.RollbackException ex) {
                transactionException = ex;
            } catch (Exception ex) {
            }
            if (transactionException == null) {
                JsfUtil.addSuccessMessage("Estado was successfully created.");
            } else {
                JsfUtil.ensureAddErrorMessage(transactionException, "A persistence error occurred.");
            }
        } catch (Exception e) {
            try {
                utx.rollback();
            } catch (Exception ex) {
            }
            JsfUtil.ensureAddErrorMessage(e, "A persistence error occurred.");
            return null;
        }
        return listSetup();
    }

    public String detailSetup() {
        return scalarSetup("estado_detail");
    }

    public String editSetup() {
        return scalarSetup("estado_edit");
    }

    private String scalarSetup(String destination) {
        reset(false);
        estado = (Estado) JsfUtil.getObjectFromRequestParameter("jsfcrud.currentEstado", converter, null);
        if (estado == null) {
            String requestEstadoString = JsfUtil.getRequestParameter("jsfcrud.currentEstado");
            JsfUtil.addErrorMessage("The estado with id " + requestEstadoString + " no longer exists.");
            return relatedOrListOutcome();
        }
        return destination;
    }

    public String edit() {
        String estadoString = converter.getAsString(FacesContext.getCurrentInstance(), null, estado);
        String currentEstadoString = JsfUtil.getRequestParameter("jsfcrud.currentEstado");
        if (estadoString == null || estadoString.length() == 0 || !estadoString.equals(currentEstadoString)) {
            String outcome = editSetup();
            if ("estado_edit".equals(outcome)) {
                JsfUtil.addErrorMessage("Could not edit estado. Try again.");
            }
            return outcome;
        }
        try {
            utx.begin();
        } catch (Exception ex) {
        }
        try {
            Exception transactionException = null;
            getJpaController().edit(estado);
            try {
                utx.commit();
            } catch (javax.transaction.RollbackException ex) {
                transactionException = ex;
            } catch (Exception ex) {
            }
            if (transactionException == null) {
                JsfUtil.addSuccessMessage("Estado was successfully updated.");
            } else {
                JsfUtil.ensureAddErrorMessage(transactionException, "A persistence error occurred.");
            }
        } catch (Exception e) {
            try {
                utx.rollback();
            } catch (Exception ex) {
            }
            JsfUtil.ensureAddErrorMessage(e, "A persistence error occurred.");
            return null;
        }
        return detailSetup();
    }

    public String remove() {
        String idAsString = JsfUtil.getRequestParameter("jsfcrud.currentEstado");
        Integer id = new Integer(idAsString);
        try {
            utx.begin();
        } catch (Exception ex) {
        }
        try {
            Exception transactionException = null;
            getJpaController().remove(getJpaController().find(id));
            try {
                utx.commit();
            } catch (javax.transaction.RollbackException ex) {
                transactionException = ex;
            } catch (Exception ex) {
            }
            if (transactionException == null) {
                JsfUtil.addSuccessMessage("Estado was successfully deleted.");
            } else {
                JsfUtil.ensureAddErrorMessage(transactionException, "A persistence error occurred.");
            }
        } catch (Exception e) {
            try {
                utx.rollback();
            } catch (Exception ex) {
            }
            JsfUtil.ensureAddErrorMessage(e, "A persistence error occurred.");
            return null;
        }
        return relatedOrListOutcome();
    }

    private String relatedOrListOutcome() {
        String relatedControllerOutcome = relatedControllerOutcome();
        if ((ERROR)) {
            return relatedControllerOutcome;
        }
        return listSetup();
    }

    public List<Estado> getEstadoItems() {
        if (estadoItems == null) {
            getPagingInfo();
            estadoItems = getJpaController().findRange(new int[]{pagingInfo.getFirstItem(), pagingInfo.getFirstItem() + pagingInfo.getBatchSize()});
        }
        return estadoItems;
    }

    public String next() {
        reset(false);
        getPagingInfo().nextPage();
        return "estado_list";
    }

    public String prev() {
        reset(false);
        getPagingInfo().previousPage();
        return "estado_list";
    }

    private String relatedControllerOutcome() {
        String relatedControllerString = JsfUtil.getRequestParameter("jsfcrud.relatedController");
        String relatedControllerTypeString = JsfUtil.getRequestParameter("jsfcrud.relatedControllerType");
        if (relatedControllerString != null && relatedControllerTypeString != null) {
            FacesContext context = FacesContext.getCurrentInstance();
            Object relatedController = context.getApplication().getELResolver().getValue(context.getELContext(), null, relatedControllerString);
            try {
                Class<?> relatedControllerType = Class.forName(relatedControllerTypeString);
                Method detailSetupMethod = relatedControllerType.getMethod("detailSetup");
                return (String) detailSetupMethod.invoke(relatedController);
            } catch (ClassNotFoundException e) {
                throw new FacesException(e);
            } catch (NoSuchMethodException e) {
                throw new FacesException(e);
            } catch (IllegalAccessException e) {
                throw new FacesException(e);
            } catch (InvocationTargetException e) {
                throw new FacesException(e);
            }
        }
        return null;
    }

    private void reset(boolean resetFirstItem) {
        estado = null;
        estadoItems = null;
        pagingInfo.setItemCount(-1);
        if (resetFirstItem) {
            pagingInfo.setFirstItem(0);
        }
    }

    public void validateCreate(FacesContext facesContext, UIComponent component, Object value) {
        Estado newEstado = new Estado();
        String newEstadoString = converter.getAsString(FacesContext.getCurrentInstance(), null, newEstado);
        String estadoString = converter.getAsString(FacesContext.getCurrentInstance(), null, estado);
        if (!newEstadoString.equals(estadoString)) {
            createSetup();
        }
    }

    public Converter getConverter() {
        return converter;
    }
    
}

Project/unops3/web/incidente/Edit.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
    <html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <title>Editing Incidente</title>
            <link rel="stylesheet" type="text/css" href="/unops3/faces/jsfcrud.css" />
        </head>
        <body>
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h1>Editing Incidente</h1>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="IdIncidente:"/>
                    <h:outputText value="#{incidente.incidente.idIncidente}" title="IdIncidente" />
                    <h:outputText value="Asunto:"/>
                    <h:inputText id="asunto" value="#{incidente.incidente.asunto}" title="Asunto" />
                    <h:outputText value="HorasSoporte:"/>
                    <h:inputText id="horasSoporte" value="#{incidente.incidente.horasSoporte}" title="HorasSoporte" />
                    <h:outputText value="Fecha (MM/dd/yyyy HH:mm:ss):"/>
                    <h:inputText id="fecha" value="#{incidente.incidente.fecha}" title="Fecha" >
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:inputText>
                    <h:outputText value="IdClasificacion:"/>
                    <h:selectOneMenu id="idClasificacion" value="#{incidente.incidente.idClasificacion}" title="IdClasificacion" required="true" requiredMessage="The idClasificacion field is required." >
                        <f:selectItems value="#{clasificacion.clasificacionItemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputText value="IdEstado:"/>
                    <h:selectOneMenu id="idEstado" value="#{incidente.incidente.idEstado}" title="IdEstado" required="true" requiredMessage="The idEstado field is required." >
                        <f:selectItems value="#{estado.estadoItemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputText value="IdPrioridad:"/>
                    <h:selectOneMenu id="idPrioridad" value="#{incidente.incidente.idPrioridad}" title="IdPrioridad" required="true" requiredMessage="The idPrioridad field is required." >
                        <f:selectItems value="#{prioridad.prioridadItemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputText value="IdUsuario:"/>
                    <h:selectOneMenu id="idUsuario" value="#{incidente.incidente.idUsuario}" title="IdUsuario" required="true" requiredMessage="The idUsuario field is required." >
                        <f:selectItems value="#{usuario.usuarioItemsAvailableSelectOne}"/>
                    </h:selectOneMenu>

                </h:panelGrid>
                <br />
                <h:commandLink action="#{incidente.edit}" value="Save">
                    <f:param name="jsfcrud.currentIncidente" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][incidente.incidente][incidente.converter].jsfcrud_invoke}"/>
                </h:commandLink>
                <br />
                <br />
                <h:commandLink action="#{incidente.detailSetup}" value="Show" immediate="true">
                    <f:param name="jsfcrud.currentIncidente" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][incidente.incidente][incidente.converter].jsfcrud_invoke}"/>
                </h:commandLink>
                <br />
                <h:commandLink action="#{incidente.listSetup}" value="Show All Incidente Items" immediate="true"/>
                <br />
                <br />
                <h:commandLink value="Index" action="welcome" immediate="true" />

            </h:form>
        </body>
    </html>
</f:view>

Project/unops3/web/incidente/List.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
    <html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <title>Listing Incidente Items</title>
            <link rel="stylesheet" type="text/css" href="/unops3/faces/jsfcrud.css" />
        </head>
        <body>
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h1>Listing Incidente Items</h1>
            <h:form styleClass="jsfcrud_list_form">
                <h:outputText escape="false" value="(No Incidente Items Found)<br />" rendered="#{incidente.pagingInfo.itemCount == 0}" />
                <h:panelGroup rendered="#{incidente.pagingInfo.itemCount > 0}">
                    <h:outputText value="Item #{incidente.pagingInfo.firstItem + 1}..#{incidente.pagingInfo.lastItem} of #{incidente.pagingInfo.itemCount}"/>&nbsp;
                    <h:commandLink action="#{incidente.prev}" value="Previous #{incidente.pagingInfo.batchSize}" rendered="#{incidente.pagingInfo.firstItem >= incidente.pagingInfo.batchSize}"/>&nbsp;
                    <h:commandLink action="#{incidente.next}" value="Next #{incidente.pagingInfo.batchSize}" rendered="#{incidente.pagingInfo.lastItem + incidente.pagingInfo.batchSize <= incidente.pagingInfo.itemCount}"/>&nbsp;
                    <h:commandLink action="#{incidente.next}" value="Remaining #{incidente.pagingInfo.itemCount - incidente.pagingInfo.lastItem}"
                                   rendered="#{incidente.pagingInfo.lastItem < incidente.pagingInfo.itemCount && incidente.pagingInfo.lastItem + incidente.pagingInfo.batchSize > incidente.pagingInfo.itemCount}"/>
                    <h:dataTable value="#{incidente.incidenteItems}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="IdIncidente"/>
                            </f:facet>
                            <h:outputText value="#{item.idIncidente}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Asunto"/>
                            </f:facet>
                            <h:outputText value="#{item.asunto}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="HorasSoporte"/>
                            </f:facet>
                            <h:outputText value="#{item.horasSoporte}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Fecha"/>
                            </f:facet>
                            <h:outputText value="#{item.fecha}">
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="IdClasificacion"/>
                            </f:facet>
                            <h:outputText value="#{item.idClasificacion}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="IdEstado"/>
                            </f:facet>
                            <h:outputText value="#{item.idEstado}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="IdPrioridad"/>
                            </f:facet>
                            <h:outputText value="#{item.idPrioridad}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="IdUsuario"/>
                            </f:facet>
                            <h:outputText value="#{item.idUsuario}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText escape="false" value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink value="Show" action="#{incidente.detailSetup}">
                                <f:param name="jsfcrud.currentIncidente" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][incidente.converter].jsfcrud_invoke}"/>
                            </h:commandLink>
                            <h:outputText value=" "/>
                            <h:commandLink value="Edit" action="#{incidente.editSetup}">
                                <f:param name="jsfcrud.currentIncidente" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][incidente.converter].jsfcrud_invoke}"/>
                            </h:commandLink>
                            <h:outputText value=" "/>
                            <h:commandLink value="Destroy" action="#{incidente.remove}">
                                <f:param name="jsfcrud.currentIncidente" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][incidente.converter].jsfcrud_invoke}"/>
                            </h:commandLink>
                        </h:column>

                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{incidente.createSetup}" value="New Incidente"/>
                <br />
                <br />
                <h:commandLink value="Index" action="welcome" immediate="true" />


            </h:form>
        </body>
    </html>
</f:view>

Project/unops3/web/incidente/New.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
    <html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <title>New Incidente</title>
            <link rel="stylesheet" type="text/css" href="/unops3/faces/jsfcrud.css" />
        </head>
        <body>
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h1>New Incidente</h1>
            <h:form>
                <h:inputHidden id="validateCreateField" validator="#{incidente.validateCreate}" value="value"/>
                <h:panelGrid columns="2">
                    <h:outputText value="IdIncidente:"/>
                    <h:inputText id="idIncidente" value="#{incidente.incidente.idIncidente}" title="IdIncidente" required="true" requiredMessage="The idIncidente field is required." />
                    <h:outputText value="Asunto:"/>
                    <h:inputText id="asunto" value="#{incidente.incidente.asunto}" title="Asunto" />
                    <h:outputText value="HorasSoporte:"/>
                    <h:inputText id="horasSoporte" value="#{incidente.incidente.horasSoporte}" title="HorasSoporte" />
                    <h:outputText value="Fecha (MM/dd/yyyy HH:mm:ss):"/>
                    <h:inputText id="fecha" value="#{incidente.incidente.fecha}" title="Fecha" >
                        <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                    </h:inputText>
                    <h:outputText value="IdClasificacion:"/>
                    <h:selectOneMenu id="idClasificacion" value="#{incidente.incidente.idClasificacion}" title="IdClasificacion" required="true" requiredMessage="The idClasificacion field is required." >
                        <f:selectItems value="#{clasificacion.clasificacionItemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputText value="IdEstado:"/>
                    <h:selectOneMenu id="idEstado" value="#{incidente.incidente.idEstado}" title="IdEstado" required="true" requiredMessage="The idEstado field is required." >
                        <f:selectItems value="#{estado.estadoItemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputText value="IdPrioridad:"/>
                    <h:selectOneMenu id="idPrioridad" value="#{incidente.incidente.idPrioridad}" title="IdPrioridad" required="true" requiredMessage="The idPrioridad field is required." >
                        <f:selectItems value="#{prioridad.prioridadItemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputText value="IdUsuario:"/>
                    <h:selectOneMenu id="idUsuario" value="#{incidente.incidente.idUsuario}" title="IdUsuario" required="true" requiredMessage="The idUsuario field is required." >
                        <f:selectItems value="#{usuario.usuarioItemsAvailableSelectOne}"/>
                    </h:selectOneMenu>

                </h:panelGrid>
                <br />
                <h:commandLink action="#{incidente.create}" value="Create"/>
                <br />
                <br />
                <h:commandLink action="#{incidente.listSetup}" value="Show All Incidente Items" immediate="true"/>
                <br />
                <br />
                <h:commandLink value="Index" action="welcome" immediate="true" />

            </h:form>
        </body>
    </html>
</f:view>