Project/unops3/src/java/unops34/UsuarioController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unops34;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.List;
import javax.faces.FacesException;
import javax.annotation.Resource;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.model.SelectItem;
import javax.persistence.EntityManagerFactory;
import javax.persistence.PersistenceUnit;
import javax.transaction.UserTransaction;
import unops34.util.JsfUtil;
import unops34.util.PagingInfo;

/**
 *
 * @author Dell
 */
public class UsuarioController {

    public UsuarioController() {
        pagingInfo = new PagingInfo();
        converter = new UsuarioConverter();
    }
    private Usuario usuario = null;
    private List<Usuario> usuarioItems = null;
    private UsuarioFacade jpaController = null;
    private UsuarioConverter converter = null;
    private PagingInfo pagingInfo = null;
    @Resource
    private UserTransaction utx = null;
    @PersistenceUnit(unitName = "unops3PU")
    private EntityManagerFactory emf = null;

    public PagingInfo getPagingInfo() {
        if (pagingInfo.getItemCount() == -1) {
            pagingInfo.setItemCount(getJpaController().count());
        }
        return pagingInfo;
    }

    public UsuarioFacade getJpaController() {
        if (jpaController == null) {
            FacesContext facesContext = FacesContext.getCurrentInstance();
            jpaController = (UsuarioFacade) facesContext.getApplication().getELResolver().getValue(facesContext.getELContext(), null, "usuarioJpa");
        }
        return jpaController;
    }

    public SelectItem[] getUsuarioItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(getJpaController().findAll(), false);
    }

    public SelectItem[] getUsuarioItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(getJpaController().findAll(), true);
    }

    public Usuario getUsuario() {
        if (usuario == null) {
            usuario = (Usuario) JsfUtil.getObjectFromRequestParameter("jsfcrud.currentUsuario", converter, null);
        }
        if (usuario == null) {
            usuario = new Usuario();
        }
        return usuario;
    }

    public String listSetup() {
        reset(true);
        return "usuario_list";
    }

    public String createSetup() {
        reset(false);
        usuario = new Usuario();
        return "usuario_create";
    }

    public String create() {
        try {
            utx.begin();
        } catch (Exception ex) {
        }
        try {
            Exception transactionException = null;
            getJpaController().create(usuario);
            try {
                utx.commit();
            } catch (javax.transaction.RollbackException ex) {
                transactionException = ex;
            } catch (Exception ex) {
            }
            if (transactionException == null) {
                JsfUtil.addSuccessMessage("Usuario was successfully created.");
            } else {
                JsfUtil.ensureAddErrorMessage(transactionException, "A persistence error occurred.");
            }
        } catch (Exception e) {
            try {
                utx.rollback();
            } catch (Exception ex) {
            }
            JsfUtil.ensureAddErrorMessage(e, "A persistence error occurred.");
            return null;
        }
        return listSetup();
    }

    public String detailSetup() {
        return scalarSetup("usuario_detail");
    }

    public String editSetup() {
        return scalarSetup("usuario_edit");
    }

    private String scalarSetup(String destination) {
        reset(false);
        usuario = (Usuario) JsfUtil.getObjectFromRequestParameter("jsfcrud.currentUsuario", converter, null);
        if (usuario == null) {
            String requestUsuarioString = JsfUtil.getRequestParameter("jsfcrud.currentUsuario");
            JsfUtil.addErrorMessage("The usuario with id " + requestUsuarioString + " no longer exists.");
            return relatedOrListOutcome();
        }
        return destination;
    }

    public String edit() {
        String usuarioString = converter.getAsString(FacesContext.getCurrentInstance(), null, usuario);
        String currentUsuarioString = JsfUtil.getRequestParameter("jsfcrud.currentUsuario");
        if (usuarioString == null || usuarioString.length() == 0 || !usuarioString.equals(currentUsuarioString)) {
            String outcome = editSetup();
            if ("usuario_edit".equals(outcome)) {
                JsfUtil.addErrorMessage("Could not edit usuario. Try again.");
            }
            return outcome;
        }
        try {
            utx.begin();
        } catch (Exception ex) {
        }
        try {
            Exception transactionException = null;
            getJpaController().edit(usuario);
            try {
                utx.commit();
            } catch (javax.transaction.RollbackException ex) {
                transactionException = ex;
            } catch (Exception ex) {
            }
            if (transactionException == null) {
                JsfUtil.addSuccessMessage("Usuario was successfully updated.");
            } else {
                JsfUtil.ensureAddErrorMessage(transactionException, "A persistence error occurred.");
            }
        } catch (Exception e) {
            try {
                utx.rollback();
            } catch (Exception ex) {
            }
            JsfUtil.ensureAddErrorMessage(e, "A persistence error occurred.");
            return null;
        }
        return detailSetup();
    }

    public String remove() {
        String idAsString = JsfUtil.getRequestParameter("jsfcrud.currentUsuario");
        Integer id = new Integer(idAsString);
        try {
            utx.begin();
        } catch (Exception ex) {
        }
        try {
            Exception transactionException = null;
            getJpaController().remove(getJpaController().find(id));
            try {
                utx.commit();
            } catch (javax.transaction.RollbackException ex) {
                transactionException = ex;
            } catch (Exception ex) {
            }
            if (transactionException == null) {
                JsfUtil.addSuccessMessage("Usuario was successfully deleted.");
            } else {
                JsfUtil.ensureAddErrorMessage(transactionException, "A persistence error occurred.");
            }
        } catch (Exception e) {
            try {
                utx.rollback();
            } catch (Exception ex) {
            }
            JsfUtil.ensureAddErrorMessage(e, "A persistence error occurred.");
            return null;
        }
        return relatedOrListOutcome();
    }

    private String relatedOrListOutcome() {
        String relatedControllerOutcome = relatedControllerOutcome();
        if ((ERROR)) {
            return relatedControllerOutcome;
        }
        return listSetup();
    }

    public List<Usuario> getUsuarioItems() {
        if (usuarioItems == null) {
            getPagingInfo();
            usuarioItems = getJpaController().findRange(new int[]{pagingInfo.getFirstItem(), pagingInfo.getFirstItem() + pagingInfo.getBatchSize()});
        }
        return usuarioItems;
    }

    public String next() {
        reset(false);
        getPagingInfo().nextPage();
        return "usuario_list";
    }

    public String prev() {
        reset(false);
        getPagingInfo().previousPage();
        return "usuario_list";
    }

    private String relatedControllerOutcome() {
        String relatedControllerString = JsfUtil.getRequestParameter("jsfcrud.relatedController");
        String relatedControllerTypeString = JsfUtil.getRequestParameter("jsfcrud.relatedControllerType");
        if (relatedControllerString != null && relatedControllerTypeString != null) {
            FacesContext context = FacesContext.getCurrentInstance();
            Object relatedController = context.getApplication().getELResolver().getValue(context.getELContext(), null, relatedControllerString);
            try {
                Class<?> relatedControllerType = Class.forName(relatedControllerTypeString);
                Method detailSetupMethod = relatedControllerType.getMethod("detailSetup");
                return (String) detailSetupMethod.invoke(relatedController);
            } catch (ClassNotFoundException e) {
                throw new FacesException(e);
            } catch (NoSuchMethodException e) {
                throw new FacesException(e);
            } catch (IllegalAccessException e) {
                throw new FacesException(e);
            } catch (InvocationTargetException e) {
                throw new FacesException(e);
            }
        }
        return null;
    }

    private void reset(boolean resetFirstItem) {
        usuario = null;
        usuarioItems = null;
        pagingInfo.setItemCount(-1);
        if (resetFirstItem) {
            pagingInfo.setFirstItem(0);
        }
    }

    public void validateCreate(FacesContext facesContext, UIComponent component, Object value) {
        Usuario newUsuario = new Usuario();
        String newUsuarioString = converter.getAsString(FacesContext.getCurrentInstance(), null, newUsuario);
        String usuarioString = converter.getAsString(FacesContext.getCurrentInstance(), null, usuario);
        if (!newUsuarioString.equals(usuarioString)) {
            createSetup();
        }
    }

    public Converter getConverter() {
        return converter;
    }
    
}

Project/unops3/web/perfil/Detail.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
    <html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <title>Perfil Detail</title>
            <link rel="stylesheet" type="text/css" href="/unops3/faces/jsfcrud.css" />
        </head>
        <body>
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h1>Perfil Detail</h1>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="IdPerfil:"/>
                    <h:outputText value="#{perfil.perfil.idPerfil}" title="IdPerfil" />
                    <h:outputText value="Descripcion:"/>
                    <h:outputText value="#{perfil.perfil.descripcion}" title="Descripcion" />

                    <h:outputText value="UsuarioCollection:" />
                    <h:panelGroup>
                        <h:outputText rendered="#{empty perfil.perfil.usuarioCollection}" value="(No Items)"/>
                        <h:dataTable value="#{perfil.perfil.usuarioCollection}" var="item" 
                                     border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px" 
                                     rendered="#{not empty perfil.perfil.usuarioCollection}">
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="IdUsuario"/>
                                </f:facet>
                                <h:outputText value="#{item.idUsuario}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="NombreUsuario"/>
                                </f:facet>
                                <h:outputText value="#{item.nombreUsuario}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="IdPerfil"/>
                                </f:facet>
                                <h:outputText value="#{item.idPerfil}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText escape="false" value="&nbsp;"/>
                                </f:facet>
                                <h:commandLink value="Show" action="#{usuario.detailSetup}">
                                    <f:param name="jsfcrud.currentPerfil" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][perfil.perfil][perfil.converter].jsfcrud_invoke}"/>
                                    <f:param name="jsfcrud.currentUsuario" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][usuario.converter].jsfcrud_invoke}"/>
                                    <f:param name="jsfcrud.relatedController" value="perfil" />
                                    <f:param name="jsfcrud.relatedControllerType" value="unops34.PerfilController" />
                                </h:commandLink>
                                <h:outputText value=" "/>
                                <h:commandLink value="Edit" action="#{usuario.editSetup}">
                                    <f:param name="jsfcrud.currentPerfil" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][perfil.perfil][perfil.converter].jsfcrud_invoke}"/>
                                    <f:param name="jsfcrud.currentUsuario" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][usuario.converter].jsfcrud_invoke}"/>
                                    <f:param name="jsfcrud.relatedController" value="perfil" />
                                    <f:param name="jsfcrud.relatedControllerType" value="unops34.PerfilController" />
                                </h:commandLink>
                                <h:outputText value=" "/>
                                <h:commandLink value="Destroy" action="#{usuario.destroy}">
                                    <f:param name="jsfcrud.currentPerfil" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][perfil.perfil][perfil.converter].jsfcrud_invoke}"/>
                                    <f:param name="jsfcrud.currentUsuario" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][usuario.converter].jsfcrud_invoke}"/>
                                    <f:param name="jsfcrud.relatedController" value="perfil" />
                                    <f:param name="jsfcrud.relatedControllerType" value="unops34.PerfilController" />
                                </h:commandLink>
                            </h:column>
                        </h:dataTable>
                    </h:panelGroup>

                </h:panelGrid>
                <br />
                <h:commandLink action="#{perfil.remove}" value="Destroy">
                    <f:param name="jsfcrud.currentPerfil" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][perfil.perfil][perfil.converter].jsfcrud_invoke}" />
                </h:commandLink>
                <br />
                <br />
                <h:commandLink action="#{perfil.editSetup}" value="Edit">
                    <f:param name="jsfcrud.currentPerfil" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][perfil.perfil][perfil.converter].jsfcrud_invoke}" />
                </h:commandLink>
                <br />
                <h:commandLink action="#{perfil.createSetup}" value="New Perfil" />
                <br />
                <h:commandLink action="#{perfil.listSetup}" value="Show All Perfil Items"/>
                <br />
                <br />
                <h:commandLink value="Index" action="welcome" immediate="true" />

            </h:form>
        </body>
    </html>
</f:view>

Project/unops3/web/perfil/Edit.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
    <html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <title>Editing Perfil</title>
            <link rel="stylesheet" type="text/css" href="/unops3/faces/jsfcrud.css" />
        </head>
        <body>
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h1>Editing Perfil</h1>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="IdPerfil:"/>
                    <h:outputText value="#{perfil.perfil.idPerfil}" title="IdPerfil" />
                    <h:outputText value="Descripcion:"/>
                    <h:inputText id="descripcion" value="#{perfil.perfil.descripcion}" title="Descripcion" />
                    <h:outputText value="UsuarioCollection:"/>
                    <h:selectManyListbox id="usuarioCollection" value="#{perfil.perfil.jsfcrud_transform[jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method.collectionToArray][jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method.arrayToList].usuarioCollection}" title="UsuarioCollection" size="6" converter="#{usuario.converter}" >
                        <f:selectItems value="#{usuario.usuarioItemsAvailableSelectMany}"/>
                    </h:selectManyListbox>

                </h:panelGrid>
                <br />
                <h:commandLink action="#{perfil.edit}" value="Save">
                    <f:param name="jsfcrud.currentPerfil" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][perfil.perfil][perfil.converter].jsfcrud_invoke}"/>
                </h:commandLink>
                <br />
                <br />
                <h:commandLink action="#{perfil.detailSetup}" value="Show" immediate="true">
                    <f:param name="jsfcrud.currentPerfil" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][perfil.perfil][perfil.converter].jsfcrud_invoke}"/>
                </h:commandLink>
                <br />
                <h:commandLink action="#{perfil.listSetup}" value="Show All Perfil Items" immediate="true"/>
                <br />
                <br />
                <h:commandLink value="Index" action="welcome" immediate="true" />

            </h:form>
        </body>
    </html>
</f:view>

Project/unops3/web/perfil/List.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
    <html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <title>Listing Perfil Items</title>
            <link rel="stylesheet" type="text/css" href="/unops3/faces/jsfcrud.css" />
        </head>
        <body>
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h1>Listing Perfil Items</h1>
            <h:form styleClass="jsfcrud_list_form">
                <h:outputText escape="false" value="(No Perfil Items Found)<br />" rendered="#{perfil.pagingInfo.itemCount == 0}" />
                <h:panelGroup rendered="#{perfil.pagingInfo.itemCount > 0}">
                    <h:outputText value="Item #{perfil.pagingInfo.firstItem + 1}..#{perfil.pagingInfo.lastItem} of #{perfil.pagingInfo.itemCount}"/>&nbsp;
                    <h:commandLink action="#{perfil.prev}" value="Previous #{perfil.pagingInfo.batchSize}" rendered="#{perfil.pagingInfo.firstItem >= perfil.pagingInfo.batchSize}"/>&nbsp;
                    <h:commandLink action="#{perfil.next}" value="Next #{perfil.pagingInfo.batchSize}" rendered="#{perfil.pagingInfo.lastItem + perfil.pagingInfo.batchSize <= perfil.pagingInfo.itemCount}"/>&nbsp;
                    <h:commandLink action="#{perfil.next}" value="Remaining #{perfil.pagingInfo.itemCount - perfil.pagingInfo.lastItem}"
                                   rendered="#{perfil.pagingInfo.lastItem < perfil.pagingInfo.itemCount && perfil.pagingInfo.lastItem + perfil.pagingInfo.batchSize > perfil.pagingInfo.itemCount}"/>
                    <h:dataTable value="#{perfil.perfilItems}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="IdPerfil"/>
                            </f:facet>
                            <h:outputText value="#{item.idPerfil}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="Descripcion"/>
                            </f:facet>
                            <h:outputText value="#{item.descripcion}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText escape="false" value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink value="Show" action="#{perfil.detailSetup}">
                                <f:param name="jsfcrud.currentPerfil" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][perfil.converter].jsfcrud_invoke}"/>
                            </h:commandLink>
                            <h:outputText value=" "/>
                            <h:commandLink value="Edit" action="#{perfil.editSetup}">
                                <f:param name="jsfcrud.currentPerfil" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][perfil.converter].jsfcrud_invoke}"/>
                            </h:commandLink>
                            <h:outputText value=" "/>
                            <h:commandLink value="Destroy" action="#{perfil.remove}">
                                <f:param name="jsfcrud.currentPerfil" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][perfil.converter].jsfcrud_invoke}"/>
                            </h:commandLink>
                        </h:column>

                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{perfil.createSetup}" value="New Perfil"/>
                <br />
                <br />
                <h:commandLink value="Index" action="welcome" immediate="true" />


            </h:form>
        </body>
    </html>
</f:view>

Project/unops3/web/perfil/New.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
    <html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <title>New Perfil</title>
            <link rel="stylesheet" type="text/css" href="/unops3/faces/jsfcrud.css" />
        </head>
        <body>
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h1>New Perfil</h1>
            <h:form>
                <h:inputHidden id="validateCreateField" validator="#{perfil.validateCreate}" value="value"/>
                <h:panelGrid columns="2">
                    <h:outputText value="IdPerfil:"/>
                    <h:inputText id="idPerfil" value="#{perfil.perfil.idPerfil}" title="IdPerfil" required="true" requiredMessage="The idPerfil field is required." />
                    <h:outputText value="Descripcion:"/>
                    <h:inputText id="descripcion" value="#{perfil.perfil.descripcion}" title="Descripcion" />
                    <h:outputText value="UsuarioCollection:"/>
                    <h:selectManyListbox id="usuarioCollection" value="#{perfil.perfil.jsfcrud_transform[jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method.collectionToArray][jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method.arrayToList].usuarioCollection}" title="UsuarioCollection" size="6" converter="#{usuario.converter}" >
                        <f:selectItems value="#{usuario.usuarioItemsAvailableSelectMany}"/>
                    </h:selectManyListbox>

                </h:panelGrid>
                <br />
                <h:commandLink action="#{perfil.create}" value="Create"/>
                <br />
                <br />
                <h:commandLink action="#{perfil.listSetup}" value="Show All Perfil Items" immediate="true"/>
                <br />
                <br />
                <h:commandLink value="Index" action="welcome" immediate="true" />

            </h:form>
        </body>
    </html>
</f:view>