Project/unops3/src/java/unops34/IncidenteController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unops34;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.List;
import javax.faces.FacesException;
import javax.annotation.Resource;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.model.SelectItem;
import javax.persistence.EntityManagerFactory;
import javax.persistence.PersistenceUnit;
import javax.transaction.UserTransaction;
import unops34.util.JsfUtil;
import unops34.util.PagingInfo;

/**
 *
 * @author Dell
 */
public class IncidenteController {

    public IncidenteController() {
        pagingInfo = new PagingInfo();
        converter = new IncidenteConverter();
    }
    private Incidente incidente = null;
    private List<Incidente> incidenteItems = null;
    private IncidenteFacade jpaController = null;
    private IncidenteConverter converter = null;
    private PagingInfo pagingInfo = null;
    @Resource
    private UserTransaction utx = null;
    @PersistenceUnit(unitName = "unops3PU")
    private EntityManagerFactory emf = null;

    public PagingInfo getPagingInfo() {
        if (pagingInfo.getItemCount() == -1) {
            pagingInfo.setItemCount(getJpaController().count());
        }
        return pagingInfo;
    }

    public IncidenteFacade getJpaController() {
        if (jpaController == null) {
            FacesContext facesContext = FacesContext.getCurrentInstance();
            jpaController = (IncidenteFacade) facesContext.getApplication().getELResolver().getValue(facesContext.getELContext(), null, "incidenteJpa");
        }
        return jpaController;
    }

    public SelectItem[] getIncidenteItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(getJpaController().findAll(), false);
    }

    public SelectItem[] getIncidenteItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(getJpaController().findAll(), true);
    }

    public Incidente getIncidente() {
        if (incidente == null) {
            incidente = (Incidente) JsfUtil.getObjectFromRequestParameter("jsfcrud.currentIncidente", converter, null);
        }
        if (incidente == null) {
            incidente = new Incidente();
        }
        return incidente;
    }

    public String listSetup() {
        reset(true);
        return "incidente_list";
    }

    public String createSetup() {
        reset(false);
        incidente = new Incidente();
        return "incidente_create";
    }

    public String create() {
        try {
            utx.begin();
        } catch (Exception ex) {
        }
        try {
            Exception transactionException = null;
            getJpaController().create(incidente);
            try {
                utx.commit();
            } catch (javax.transaction.RollbackException ex) {
                transactionException = ex;
            } catch (Exception ex) {
            }
            if (transactionException == null) {
                JsfUtil.addSuccessMessage("Incidente was successfully created.");
            } else {
                JsfUtil.ensureAddErrorMessage(transactionException, "A persistence error occurred.");
            }
        } catch (Exception e) {
            try {
                utx.rollback();
            } catch (Exception ex) {
            }
            JsfUtil.ensureAddErrorMessage(e, "A persistence error occurred.");
            return null;
        }
        return listSetup();
    }

    public String detailSetup() {
        return scalarSetup("incidente_detail");
    }

    public String editSetup() {
        return scalarSetup("incidente_edit");
    }

    private String scalarSetup(String destination) {
        reset(false);
        incidente = (Incidente) JsfUtil.getObjectFromRequestParameter("jsfcrud.currentIncidente", converter, null);
        if (incidente == null) {
            String requestIncidenteString = JsfUtil.getRequestParameter("jsfcrud.currentIncidente");
            JsfUtil.addErrorMessage("The incidente with id " + requestIncidenteString + " no longer exists.");
            return relatedOrListOutcome();
        }
        return destination;
    }

    public String edit() {
        String incidenteString = converter.getAsString(FacesContext.getCurrentInstance(), null, incidente);
        String currentIncidenteString = JsfUtil.getRequestParameter("jsfcrud.currentIncidente");
        if (incidenteString == null || incidenteString.length() == 0 || !incidenteString.equals(currentIncidenteString)) {
            String outcome = editSetup();
            if ("incidente_edit".equals(outcome)) {
                JsfUtil.addErrorMessage("Could not edit incidente. Try again.");
            }
            return outcome;
        }
        try {
            utx.begin();
        } catch (Exception ex) {
        }
        try {
            Exception transactionException = null;
            getJpaController().edit(incidente);
            try {
                utx.commit();
            } catch (javax.transaction.RollbackException ex) {
                transactionException = ex;
            } catch (Exception ex) {
            }
            if (transactionException == null) {
                JsfUtil.addSuccessMessage("Incidente was successfully updated.");
            } else {
                JsfUtil.ensureAddErrorMessage(transactionException, "A persistence error occurred.");
            }
        } catch (Exception e) {
            try {
                utx.rollback();
            } catch (Exception ex) {
            }
            JsfUtil.ensureAddErrorMessage(e, "A persistence error occurred.");
            return null;
        }
        return detailSetup();
    }

    public String remove() {
        String idAsString = JsfUtil.getRequestParameter("jsfcrud.currentIncidente");
        Integer id = new Integer(idAsString);
        try {
            utx.begin();
        } catch (Exception ex) {
        }
        try {
            Exception transactionException = null;
            getJpaController().remove(getJpaController().find(id));
            try {
                utx.commit();
            } catch (javax.transaction.RollbackException ex) {
                transactionException = ex;
            } catch (Exception ex) {
            }
            if (transactionException == null) {
                JsfUtil.addSuccessMessage("Incidente was successfully deleted.");
            } else {
                JsfUtil.ensureAddErrorMessage(transactionException, "A persistence error occurred.");
            }
        } catch (Exception e) {
            try {
                utx.rollback();
            } catch (Exception ex) {
            }
            JsfUtil.ensureAddErrorMessage(e, "A persistence error occurred.");
            return null;
        }
        return relatedOrListOutcome();
    }

    private String relatedOrListOutcome() {
        String relatedControllerOutcome = relatedControllerOutcome();
        if ((ERROR)) {
            return relatedControllerOutcome;
        }
        return listSetup();
    }

    public List<Incidente> getIncidenteItems() {
        if (incidenteItems == null) {
            getPagingInfo();
            incidenteItems = getJpaController().findRange(new int[]{pagingInfo.getFirstItem(), pagingInfo.getFirstItem() + pagingInfo.getBatchSize()});
        }
        return incidenteItems;
    }

    public String next() {
        reset(false);
        getPagingInfo().nextPage();
        return "incidente_list";
    }

    public String prev() {
        reset(false);
        getPagingInfo().previousPage();
        return "incidente_list";
    }

    private String relatedControllerOutcome() {
        String relatedControllerString = JsfUtil.getRequestParameter("jsfcrud.relatedController");
        String relatedControllerTypeString = JsfUtil.getRequestParameter("jsfcrud.relatedControllerType");
        if (relatedControllerString != null && relatedControllerTypeString != null) {
            FacesContext context = FacesContext.getCurrentInstance();
            Object relatedController = context.getApplication().getELResolver().getValue(context.getELContext(), null, relatedControllerString);
            try {
                Class<?> relatedControllerType = Class.forName(relatedControllerTypeString);
                Method detailSetupMethod = relatedControllerType.getMethod("detailSetup");
                return (String) detailSetupMethod.invoke(relatedController);
            } catch (ClassNotFoundException e) {
                throw new FacesException(e);
            } catch (NoSuchMethodException e) {
                throw new FacesException(e);
            } catch (IllegalAccessException e) {
                throw new FacesException(e);
            } catch (InvocationTargetException e) {
                throw new FacesException(e);
            }
        }
        return null;
    }

    private void reset(boolean resetFirstItem) {
        incidente = null;
        incidenteItems = null;
        pagingInfo.setItemCount(-1);
        if (resetFirstItem) {
            pagingInfo.setFirstItem(0);
        }
    }

    public void validateCreate(FacesContext facesContext, UIComponent component, Object value) {
        Incidente newIncidente = new Incidente();
        String newIncidenteString = converter.getAsString(FacesContext.getCurrentInstance(), null, newIncidente);
        String incidenteString = converter.getAsString(FacesContext.getCurrentInstance(), null, incidente);
        if (!newIncidenteString.equals(incidenteString)) {
            createSetup();
        }
    }

    public Converter getConverter() {
        return converter;
    }
    
}

Project/unops3/web/clasificacion/Detail.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
    <html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <title>Clasificacion Detail</title>
            <link rel="stylesheet" type="text/css" href="/unops3/faces/jsfcrud.css" />
        </head>
        <body>
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h1>Clasificacion Detail</h1>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="IdClasificacion:"/>
                    <h:outputText value="#{clasificacion.clasificacion.idClasificacion}" title="IdClasificacion" />
                    <h:outputText value="DescripcionClasificacion:"/>
                    <h:outputText value="#{clasificacion.clasificacion.descripcionClasificacion}" title="DescripcionClasificacion" />

                    <h:outputText value="IncidenteCollection:" />
                    <h:panelGroup>
                        <h:outputText rendered="#{empty clasificacion.clasificacion.incidenteCollection}" value="(No Items)"/>
                        <h:dataTable value="#{clasificacion.clasificacion.incidenteCollection}" var="item" 
                                     border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px" 
                                     rendered="#{not empty clasificacion.clasificacion.incidenteCollection}">
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="IdIncidente"/>
                                </f:facet>
                                <h:outputText value="#{item.idIncidente}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="Asunto"/>
                                </f:facet>
                                <h:outputText value="#{item.asunto}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="HorasSoporte"/>
                                </f:facet>
                                <h:outputText value="#{item.horasSoporte}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="Fecha"/>
                                </f:facet>
                                <h:outputText value="#{item.fecha}">
                                    <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                                </h:outputText>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="IdClasificacion"/>
                                </f:facet>
                                <h:outputText value="#{item.idClasificacion}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="IdEstado"/>
                                </f:facet>
                                <h:outputText value="#{item.idEstado}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="IdPrioridad"/>
                                </f:facet>
                                <h:outputText value="#{item.idPrioridad}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="IdUsuario"/>
                                </f:facet>
                                <h:outputText value="#{item.idUsuario}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText escape="false" value="&nbsp;"/>
                                </f:facet>
                                <h:commandLink value="Show" action="#{incidente.detailSetup}">
                                    <f:param name="jsfcrud.currentClasificacion" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][clasificacion.clasificacion][clasificacion.converter].jsfcrud_invoke}"/>
                                    <f:param name="jsfcrud.currentIncidente" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][incidente.converter].jsfcrud_invoke}"/>
                                    <f:param name="jsfcrud.relatedController" value="clasificacion" />
                                    <f:param name="jsfcrud.relatedControllerType" value="unops34.ClasificacionController" />
                                </h:commandLink>
                                <h:outputText value=" "/>
                                <h:commandLink value="Edit" action="#{incidente.editSetup}">
                                    <f:param name="jsfcrud.currentClasificacion" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][clasificacion.clasificacion][clasificacion.converter].jsfcrud_invoke}"/>
                                    <f:param name="jsfcrud.currentIncidente" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][incidente.converter].jsfcrud_invoke}"/>
                                    <f:param name="jsfcrud.relatedController" value="clasificacion" />
                                    <f:param name="jsfcrud.relatedControllerType" value="unops34.ClasificacionController" />
                                </h:commandLink>
                                <h:outputText value=" "/>
                                <h:commandLink value="Destroy" action="#{incidente.destroy}">
                                    <f:param name="jsfcrud.currentClasificacion" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][clasificacion.clasificacion][clasificacion.converter].jsfcrud_invoke}"/>
                                    <f:param name="jsfcrud.currentIncidente" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][incidente.converter].jsfcrud_invoke}"/>
                                    <f:param name="jsfcrud.relatedController" value="clasificacion" />
                                    <f:param name="jsfcrud.relatedControllerType" value="unops34.ClasificacionController" />
                                </h:commandLink>
                            </h:column>
                        </h:dataTable>
                    </h:panelGroup>

                </h:panelGrid>
                <br />
                <h:commandLink action="#{clasificacion.remove}" value="Destroy">
                    <f:param name="jsfcrud.currentClasificacion" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][clasificacion.clasificacion][clasificacion.converter].jsfcrud_invoke}" />
                </h:commandLink>
                <br />
                <br />
                <h:commandLink action="#{clasificacion.editSetup}" value="Edit">
                    <f:param name="jsfcrud.currentClasificacion" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][clasificacion.clasificacion][clasificacion.converter].jsfcrud_invoke}" />
                </h:commandLink>
                <br />
                <h:commandLink action="#{clasificacion.createSetup}" value="New Clasificacion" />
                <br />
                <h:commandLink action="#{clasificacion.listSetup}" value="Show All Clasificacion Items"/>
                <br />
                <br />
                <h:commandLink value="Index" action="welcome" immediate="true" />

            </h:form>
        </body>
    </html>
</f:view>

Project/unops3/web/clasificacion/Edit.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
    <html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <title>Editing Clasificacion</title>
            <link rel="stylesheet" type="text/css" href="/unops3/faces/jsfcrud.css" />
        </head>
        <body>
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h1>Editing Clasificacion</h1>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="IdClasificacion:"/>
                    <h:outputText value="#{clasificacion.clasificacion.idClasificacion}" title="IdClasificacion" />
                    <h:outputText value="DescripcionClasificacion:"/>
                    <h:inputText id="descripcionClasificacion" value="#{clasificacion.clasificacion.descripcionClasificacion}" title="DescripcionClasificacion" />
                    <h:outputText value="IncidenteCollection:"/>
                    <h:selectManyListbox id="incidenteCollection" value="#{clasificacion.clasificacion.jsfcrud_transform[jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method.collectionToArray][jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method.arrayToList].incidenteCollection}" title="IncidenteCollection" size="6" converter="#{incidente.converter}" >
                        <f:selectItems value="#{incidente.incidenteItemsAvailableSelectMany}"/>
                    </h:selectManyListbox>

                </h:panelGrid>
                <br />
                <h:commandLink action="#{clasificacion.edit}" value="Save">
                    <f:param name="jsfcrud.currentClasificacion" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][clasificacion.clasificacion][clasificacion.converter].jsfcrud_invoke}"/>
                </h:commandLink>
                <br />
                <br />
                <h:commandLink action="#{clasificacion.detailSetup}" value="Show" immediate="true">
                    <f:param name="jsfcrud.currentClasificacion" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][clasificacion.clasificacion][clasificacion.converter].jsfcrud_invoke}"/>
                </h:commandLink>
                <br />
                <h:commandLink action="#{clasificacion.listSetup}" value="Show All Clasificacion Items" immediate="true"/>
                <br />
                <br />
                <h:commandLink value="Index" action="welcome" immediate="true" />

            </h:form>
        </body>
    </html>
</f:view>

Project/unops3/web/clasificacion/List.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
    <html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <title>Listing Clasificacion Items</title>
            <link rel="stylesheet" type="text/css" href="/unops3/faces/jsfcrud.css" />
        </head>
        <body>
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h1>Listing Clasificacion Items</h1>
            <h:form styleClass="jsfcrud_list_form">
                <h:outputText escape="false" value="(No Clasificacion Items Found)<br />" rendered="#{clasificacion.pagingInfo.itemCount == 0}" />
                <h:panelGroup rendered="#{clasificacion.pagingInfo.itemCount > 0}">
                    <h:outputText value="Item #{clasificacion.pagingInfo.firstItem + 1}..#{clasificacion.pagingInfo.lastItem} of #{clasificacion.pagingInfo.itemCount}"/>&nbsp;
                    <h:commandLink action="#{clasificacion.prev}" value="Previous #{clasificacion.pagingInfo.batchSize}" rendered="#{clasificacion.pagingInfo.firstItem >= clasificacion.pagingInfo.batchSize}"/>&nbsp;
                    <h:commandLink action="#{clasificacion.next}" value="Next #{clasificacion.pagingInfo.batchSize}" rendered="#{clasificacion.pagingInfo.lastItem + clasificacion.pagingInfo.batchSize <= clasificacion.pagingInfo.itemCount}"/>&nbsp;
                    <h:commandLink action="#{clasificacion.next}" value="Remaining #{clasificacion.pagingInfo.itemCount - clasificacion.pagingInfo.lastItem}"
                                   rendered="#{clasificacion.pagingInfo.lastItem < clasificacion.pagingInfo.itemCount && clasificacion.pagingInfo.lastItem + clasificacion.pagingInfo.batchSize > clasificacion.pagingInfo.itemCount}"/>
                    <h:dataTable value="#{clasificacion.clasificacionItems}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="IdClasificacion"/>
                            </f:facet>
                            <h:outputText value="#{item.idClasificacion}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="DescripcionClasificacion"/>
                            </f:facet>
                            <h:outputText value="#{item.descripcionClasificacion}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText escape="false" value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink value="Show" action="#{clasificacion.detailSetup}">
                                <f:param name="jsfcrud.currentClasificacion" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][clasificacion.converter].jsfcrud_invoke}"/>
                            </h:commandLink>
                            <h:outputText value=" "/>
                            <h:commandLink value="Edit" action="#{clasificacion.editSetup}">
                                <f:param name="jsfcrud.currentClasificacion" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][clasificacion.converter].jsfcrud_invoke}"/>
                            </h:commandLink>
                            <h:outputText value=" "/>
                            <h:commandLink value="Destroy" action="#{clasificacion.remove}">
                                <f:param name="jsfcrud.currentClasificacion" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][clasificacion.converter].jsfcrud_invoke}"/>
                            </h:commandLink>
                        </h:column>

                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{clasificacion.createSetup}" value="New Clasificacion"/>
                <br />
                <br />
                <h:commandLink value="Index" action="welcome" immediate="true" />


            </h:form>
        </body>
    </html>
</f:view>

Project/unops3/web/clasificacion/New.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
    <html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <title>New Clasificacion</title>
            <link rel="stylesheet" type="text/css" href="/unops3/faces/jsfcrud.css" />
        </head>
        <body>
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h1>New Clasificacion</h1>
            <h:form>
                <h:inputHidden id="validateCreateField" validator="#{clasificacion.validateCreate}" value="value"/>
                <h:panelGrid columns="2">
                    <h:outputText value="IdClasificacion:"/>
                    <h:inputText id="idClasificacion" value="#{clasificacion.clasificacion.idClasificacion}" title="IdClasificacion" required="true" requiredMessage="The idClasificacion field is required." />
                    <h:outputText value="DescripcionClasificacion:"/>
                    <h:inputText id="descripcionClasificacion" value="#{clasificacion.clasificacion.descripcionClasificacion}" title="DescripcionClasificacion" />
                    <h:outputText value="IncidenteCollection:"/>
                    <h:selectManyListbox id="incidenteCollection" value="#{clasificacion.clasificacion.jsfcrud_transform[jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method.collectionToArray][jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method.arrayToList].incidenteCollection}" title="IncidenteCollection" size="6" converter="#{incidente.converter}" >
                        <f:selectItems value="#{incidente.incidenteItemsAvailableSelectMany}"/>
                    </h:selectManyListbox>

                </h:panelGrid>
                <br />
                <h:commandLink action="#{clasificacion.create}" value="Create"/>
                <br />
                <br />
                <h:commandLink action="#{clasificacion.listSetup}" value="Show All Clasificacion Items" immediate="true"/>
                <br />
                <br />
                <h:commandLink value="Index" action="welcome" immediate="true" />

            </h:form>
        </body>
    </html>
</f:view>