Project/unops3/src/java/unops34/PerfilController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package unops34;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.List;
import javax.faces.FacesException;
import javax.annotation.Resource;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.model.SelectItem;
import javax.persistence.EntityManagerFactory;
import javax.persistence.PersistenceUnit;
import javax.transaction.UserTransaction;
import unops34.util.JsfUtil;
import unops34.util.PagingInfo;

/**
 *
 * @author Dell
 */
public class PerfilController {

    public PerfilController() {
        pagingInfo = new PagingInfo();
        converter = new PerfilConverter();
    }
    private Perfil perfil = null;
    private List<Perfil> perfilItems = null;
    private PerfilFacade jpaController = null;
    private PerfilConverter converter = null;
    private PagingInfo pagingInfo = null;
    @Resource
    private UserTransaction utx = null;
    @PersistenceUnit(unitName = "unops3PU")
    private EntityManagerFactory emf = null;

    public PagingInfo getPagingInfo() {
        if (pagingInfo.getItemCount() == -1) {
            pagingInfo.setItemCount(getJpaController().count());
        }
        return pagingInfo;
    }

    public PerfilFacade getJpaController() {
        if (jpaController == null) {
            FacesContext facesContext = FacesContext.getCurrentInstance();
            jpaController = (PerfilFacade) facesContext.getApplication().getELResolver().getValue(facesContext.getELContext(), null, "perfilJpa");
        }
        return jpaController;
    }

    public SelectItem[] getPerfilItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(getJpaController().findAll(), false);
    }

    public SelectItem[] getPerfilItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(getJpaController().findAll(), true);
    }

    public Perfil getPerfil() {
        if (perfil == null) {
            perfil = (Perfil) JsfUtil.getObjectFromRequestParameter("jsfcrud.currentPerfil", converter, null);
        }
        if (perfil == null) {
            perfil = new Perfil();
        }
        return perfil;
    }

    public String listSetup() {
        reset(true);
        return "perfil_list";
    }

    public String createSetup() {
        reset(false);
        perfil = new Perfil();
        return "perfil_create";
    }

    public String create() {
        try {
            utx.begin();
        } catch (Exception ex) {
        }
        try {
            Exception transactionException = null;
            getJpaController().create(perfil);
            try {
                utx.commit();
            } catch (javax.transaction.RollbackException ex) {
                transactionException = ex;
            } catch (Exception ex) {
            }
            if (transactionException == null) {
                JsfUtil.addSuccessMessage("Perfil was successfully created.");
            } else {
                JsfUtil.ensureAddErrorMessage(transactionException, "A persistence error occurred.");
            }
        } catch (Exception e) {
            try {
                utx.rollback();
            } catch (Exception ex) {
            }
            JsfUtil.ensureAddErrorMessage(e, "A persistence error occurred.");
            return null;
        }
        return listSetup();
    }

    public String detailSetup() {
        return scalarSetup("perfil_detail");
    }

    public String editSetup() {
        return scalarSetup("perfil_edit");
    }

    private String scalarSetup(String destination) {
        reset(false);
        perfil = (Perfil) JsfUtil.getObjectFromRequestParameter("jsfcrud.currentPerfil", converter, null);
        if (perfil == null) {
            String requestPerfilString = JsfUtil.getRequestParameter("jsfcrud.currentPerfil");
            JsfUtil.addErrorMessage("The perfil with id " + requestPerfilString + " no longer exists.");
            return relatedOrListOutcome();
        }
        return destination;
    }

    public String edit() {
        String perfilString = converter.getAsString(FacesContext.getCurrentInstance(), null, perfil);
        String currentPerfilString = JsfUtil.getRequestParameter("jsfcrud.currentPerfil");
        if (perfilString == null || perfilString.length() == 0 || !perfilString.equals(currentPerfilString)) {
            String outcome = editSetup();
            if ("perfil_edit".equals(outcome)) {
                JsfUtil.addErrorMessage("Could not edit perfil. Try again.");
            }
            return outcome;
        }
        try {
            utx.begin();
        } catch (Exception ex) {
        }
        try {
            Exception transactionException = null;
            getJpaController().edit(perfil);
            try {
                utx.commit();
            } catch (javax.transaction.RollbackException ex) {
                transactionException = ex;
            } catch (Exception ex) {
            }
            if (transactionException == null) {
                JsfUtil.addSuccessMessage("Perfil was successfully updated.");
            } else {
                JsfUtil.ensureAddErrorMessage(transactionException, "A persistence error occurred.");
            }
        } catch (Exception e) {
            try {
                utx.rollback();
            } catch (Exception ex) {
            }
            JsfUtil.ensureAddErrorMessage(e, "A persistence error occurred.");
            return null;
        }
        return detailSetup();
    }

    public String remove() {
        String idAsString = JsfUtil.getRequestParameter("jsfcrud.currentPerfil");
        Integer id = new Integer(idAsString);
        try {
            utx.begin();
        } catch (Exception ex) {
        }
        try {
            Exception transactionException = null;
            getJpaController().remove(getJpaController().find(id));
            try {
                utx.commit();
            } catch (javax.transaction.RollbackException ex) {
                transactionException = ex;
            } catch (Exception ex) {
            }
            if (transactionException == null) {
                JsfUtil.addSuccessMessage("Perfil was successfully deleted.");
            } else {
                JsfUtil.ensureAddErrorMessage(transactionException, "A persistence error occurred.");
            }
        } catch (Exception e) {
            try {
                utx.rollback();
            } catch (Exception ex) {
            }
            JsfUtil.ensureAddErrorMessage(e, "A persistence error occurred.");
            return null;
        }
        return relatedOrListOutcome();
    }

    private String relatedOrListOutcome() {
        String relatedControllerOutcome = relatedControllerOutcome();
        if ((ERROR)) {
            return relatedControllerOutcome;
        }
        return listSetup();
    }

    public List<Perfil> getPerfilItems() {
        if (perfilItems == null) {
            getPagingInfo();
            perfilItems = getJpaController().findRange(new int[]{pagingInfo.getFirstItem(), pagingInfo.getFirstItem() + pagingInfo.getBatchSize()});
        }
        return perfilItems;
    }

    public String next() {
        reset(false);
        getPagingInfo().nextPage();
        return "perfil_list";
    }

    public String prev() {
        reset(false);
        getPagingInfo().previousPage();
        return "perfil_list";
    }

    private String relatedControllerOutcome() {
        String relatedControllerString = JsfUtil.getRequestParameter("jsfcrud.relatedController");
        String relatedControllerTypeString = JsfUtil.getRequestParameter("jsfcrud.relatedControllerType");
        if (relatedControllerString != null && relatedControllerTypeString != null) {
            FacesContext context = FacesContext.getCurrentInstance();
            Object relatedController = context.getApplication().getELResolver().getValue(context.getELContext(), null, relatedControllerString);
            try {
                Class<?> relatedControllerType = Class.forName(relatedControllerTypeString);
                Method detailSetupMethod = relatedControllerType.getMethod("detailSetup");
                return (String) detailSetupMethod.invoke(relatedController);
            } catch (ClassNotFoundException e) {
                throw new FacesException(e);
            } catch (NoSuchMethodException e) {
                throw new FacesException(e);
            } catch (IllegalAccessException e) {
                throw new FacesException(e);
            } catch (InvocationTargetException e) {
                throw new FacesException(e);
            }
        }
        return null;
    }

    private void reset(boolean resetFirstItem) {
        perfil = null;
        perfilItems = null;
        pagingInfo.setItemCount(-1);
        if (resetFirstItem) {
            pagingInfo.setFirstItem(0);
        }
    }

    public void validateCreate(FacesContext facesContext, UIComponent component, Object value) {
        Perfil newPerfil = new Perfil();
        String newPerfilString = converter.getAsString(FacesContext.getCurrentInstance(), null, newPerfil);
        String perfilString = converter.getAsString(FacesContext.getCurrentInstance(), null, perfil);
        if (!newPerfilString.equals(perfilString)) {
            createSetup();
        }
    }

    public Converter getConverter() {
        return converter;
    }
    
}

Project/unops3/web/usuario/Detail.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
    <html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <title>Usuario Detail</title>
            <link rel="stylesheet" type="text/css" href="/unops3/faces/jsfcrud.css" />
        </head>
        <body>
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h1>Usuario Detail</h1>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="IdUsuario:"/>
                    <h:outputText value="#{usuario.usuario.idUsuario}" title="IdUsuario" />
                    <h:outputText value="NombreUsuario:"/>
                    <h:outputText value="#{usuario.usuario.nombreUsuario}" title="NombreUsuario" />
                    <h:outputText value="IdPerfil:"/>
                    <h:panelGroup>
                        <h:outputText value="#{usuario.usuario.idPerfil}"/>
                        <h:panelGroup rendered="#{usuario.usuario.idPerfil != null}">
                            <h:outputText value=" ("/>
                            <h:commandLink value="Show" action="#{perfil.detailSetup}">
                                <f:param name="jsfcrud.currentUsuario" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][usuario.usuario][usuario.converter].jsfcrud_invoke}"/>
                                <f:param name="jsfcrud.currentPerfil" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][usuario.usuario.idPerfil][perfil.converter].jsfcrud_invoke}"/>
                                <f:param name="jsfcrud.relatedController" value="usuario"/>
                                <f:param name="jsfcrud.relatedControllerType" value="unops34.UsuarioController"/>
                            </h:commandLink>
                            <h:outputText value=" "/>
                            <h:commandLink value="Edit" action="#{perfil.editSetup}">
                                <f:param name="jsfcrud.currentUsuario" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][usuario.usuario][usuario.converter].jsfcrud_invoke}"/>
                                <f:param name="jsfcrud.currentPerfil" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][usuario.usuario.idPerfil][perfil.converter].jsfcrud_invoke}"/>
                                <f:param name="jsfcrud.relatedController" value="usuario"/>
                                <f:param name="jsfcrud.relatedControllerType" value="unops34.UsuarioController"/>
                            </h:commandLink>
                            <h:outputText value=" "/>
                            <h:commandLink value="Destroy" action="#{perfil.destroy}">
                                <f:param name="jsfcrud.currentUsuario" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][usuario.usuario][usuario.converter].jsfcrud_invoke}"/>
                                <f:param name="jsfcrud.currentPerfil" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][usuario.usuario.idPerfil][perfil.converter].jsfcrud_invoke}"/>
                                <f:param name="jsfcrud.relatedController" value="usuario"/>
                                <f:param name="jsfcrud.relatedControllerType" value="unops34.UsuarioController"/>
                            </h:commandLink>
                            <h:outputText value=" )"/>
                        </h:panelGroup>
                    </h:panelGroup>

                    <h:outputText value="IncidenteCollection:" />
                    <h:panelGroup>
                        <h:outputText rendered="#{empty usuario.usuario.incidenteCollection}" value="(No Items)"/>
                        <h:dataTable value="#{usuario.usuario.incidenteCollection}" var="item" 
                                     border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px" 
                                     rendered="#{not empty usuario.usuario.incidenteCollection}">
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="IdIncidente"/>
                                </f:facet>
                                <h:outputText value="#{item.idIncidente}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="Asunto"/>
                                </f:facet>
                                <h:outputText value="#{item.asunto}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="HorasSoporte"/>
                                </f:facet>
                                <h:outputText value="#{item.horasSoporte}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="Fecha"/>
                                </f:facet>
                                <h:outputText value="#{item.fecha}">
                                    <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                                </h:outputText>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="IdClasificacion"/>
                                </f:facet>
                                <h:outputText value="#{item.idClasificacion}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="IdEstado"/>
                                </f:facet>
                                <h:outputText value="#{item.idEstado}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="IdPrioridad"/>
                                </f:facet>
                                <h:outputText value="#{item.idPrioridad}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText value="IdUsuario"/>
                                </f:facet>
                                <h:outputText value="#{item.idUsuario}"/>
                            </h:column>
                            <h:column>
                                <f:facet name="header">
                                    <h:outputText escape="false" value="&nbsp;"/>
                                </f:facet>
                                <h:commandLink value="Show" action="#{incidente.detailSetup}">
                                    <f:param name="jsfcrud.currentUsuario" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][usuario.usuario][usuario.converter].jsfcrud_invoke}"/>
                                    <f:param name="jsfcrud.currentIncidente" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][incidente.converter].jsfcrud_invoke}"/>
                                    <f:param name="jsfcrud.relatedController" value="usuario" />
                                    <f:param name="jsfcrud.relatedControllerType" value="unops34.UsuarioController" />
                                </h:commandLink>
                                <h:outputText value=" "/>
                                <h:commandLink value="Edit" action="#{incidente.editSetup}">
                                    <f:param name="jsfcrud.currentUsuario" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][usuario.usuario][usuario.converter].jsfcrud_invoke}"/>
                                    <f:param name="jsfcrud.currentIncidente" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][incidente.converter].jsfcrud_invoke}"/>
                                    <f:param name="jsfcrud.relatedController" value="usuario" />
                                    <f:param name="jsfcrud.relatedControllerType" value="unops34.UsuarioController" />
                                </h:commandLink>
                                <h:outputText value=" "/>
                                <h:commandLink value="Destroy" action="#{incidente.destroy}">
                                    <f:param name="jsfcrud.currentUsuario" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][usuario.usuario][usuario.converter].jsfcrud_invoke}"/>
                                    <f:param name="jsfcrud.currentIncidente" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][incidente.converter].jsfcrud_invoke}"/>
                                    <f:param name="jsfcrud.relatedController" value="usuario" />
                                    <f:param name="jsfcrud.relatedControllerType" value="unops34.UsuarioController" />
                                </h:commandLink>
                            </h:column>
                        </h:dataTable>
                    </h:panelGroup>

                </h:panelGrid>
                <br />
                <h:commandLink action="#{usuario.remove}" value="Destroy">
                    <f:param name="jsfcrud.currentUsuario" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][usuario.usuario][usuario.converter].jsfcrud_invoke}" />
                </h:commandLink>
                <br />
                <br />
                <h:commandLink action="#{usuario.editSetup}" value="Edit">
                    <f:param name="jsfcrud.currentUsuario" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][usuario.usuario][usuario.converter].jsfcrud_invoke}" />
                </h:commandLink>
                <br />
                <h:commandLink action="#{usuario.createSetup}" value="New Usuario" />
                <br />
                <h:commandLink action="#{usuario.listSetup}" value="Show All Usuario Items"/>
                <br />
                <br />
                <h:commandLink value="Index" action="welcome" immediate="true" />

            </h:form>
        </body>
    </html>
</f:view>

Project/unops3/web/usuario/Edit.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
    <html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <title>Editing Usuario</title>
            <link rel="stylesheet" type="text/css" href="/unops3/faces/jsfcrud.css" />
        </head>
        <body>
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h1>Editing Usuario</h1>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="IdUsuario:"/>
                    <h:outputText value="#{usuario.usuario.idUsuario}" title="IdUsuario" />
                    <h:outputText value="NombreUsuario:"/>
                    <h:inputText id="nombreUsuario" value="#{usuario.usuario.nombreUsuario}" title="NombreUsuario" />
                    <h:outputText value="IncidenteCollection:"/>
                    <h:selectManyListbox id="incidenteCollection" value="#{usuario.usuario.jsfcrud_transform[jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method.collectionToArray][jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method.arrayToList].incidenteCollection}" title="IncidenteCollection" size="6" converter="#{incidente.converter}" >
                        <f:selectItems value="#{incidente.incidenteItemsAvailableSelectMany}"/>
                    </h:selectManyListbox>
                    <h:outputText value="IdPerfil:"/>
                    <h:selectOneMenu id="idPerfil" value="#{usuario.usuario.idPerfil}" title="IdPerfil" required="true" requiredMessage="The idPerfil field is required." >
                        <f:selectItems value="#{perfil.perfilItemsAvailableSelectOne}"/>
                    </h:selectOneMenu>

                </h:panelGrid>
                <br />
                <h:commandLink action="#{usuario.edit}" value="Save">
                    <f:param name="jsfcrud.currentUsuario" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][usuario.usuario][usuario.converter].jsfcrud_invoke}"/>
                </h:commandLink>
                <br />
                <br />
                <h:commandLink action="#{usuario.detailSetup}" value="Show" immediate="true">
                    <f:param name="jsfcrud.currentUsuario" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][usuario.usuario][usuario.converter].jsfcrud_invoke}"/>
                </h:commandLink>
                <br />
                <h:commandLink action="#{usuario.listSetup}" value="Show All Usuario Items" immediate="true"/>
                <br />
                <br />
                <h:commandLink value="Index" action="welcome" immediate="true" />

            </h:form>
        </body>
    </html>
</f:view>

Project/unops3/web/usuario/List.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
    <html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <title>Listing Usuario Items</title>
            <link rel="stylesheet" type="text/css" href="/unops3/faces/jsfcrud.css" />
        </head>
        <body>
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h1>Listing Usuario Items</h1>
            <h:form styleClass="jsfcrud_list_form">
                <h:outputText escape="false" value="(No Usuario Items Found)<br />" rendered="#{usuario.pagingInfo.itemCount == 0}" />
                <h:panelGroup rendered="#{usuario.pagingInfo.itemCount > 0}">
                    <h:outputText value="Item #{usuario.pagingInfo.firstItem + 1}..#{usuario.pagingInfo.lastItem} of #{usuario.pagingInfo.itemCount}"/>&nbsp;
                    <h:commandLink action="#{usuario.prev}" value="Previous #{usuario.pagingInfo.batchSize}" rendered="#{usuario.pagingInfo.firstItem >= usuario.pagingInfo.batchSize}"/>&nbsp;
                    <h:commandLink action="#{usuario.next}" value="Next #{usuario.pagingInfo.batchSize}" rendered="#{usuario.pagingInfo.lastItem + usuario.pagingInfo.batchSize <= usuario.pagingInfo.itemCount}"/>&nbsp;
                    <h:commandLink action="#{usuario.next}" value="Remaining #{usuario.pagingInfo.itemCount - usuario.pagingInfo.lastItem}"
                                   rendered="#{usuario.pagingInfo.lastItem < usuario.pagingInfo.itemCount && usuario.pagingInfo.lastItem + usuario.pagingInfo.batchSize > usuario.pagingInfo.itemCount}"/>
                    <h:dataTable value="#{usuario.usuarioItems}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="IdUsuario"/>
                            </f:facet>
                            <h:outputText value="#{item.idUsuario}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="NombreUsuario"/>
                            </f:facet>
                            <h:outputText value="#{item.nombreUsuario}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="IdPerfil"/>
                            </f:facet>
                            <h:outputText value="#{item.idPerfil}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText escape="false" value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink value="Show" action="#{usuario.detailSetup}">
                                <f:param name="jsfcrud.currentUsuario" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][usuario.converter].jsfcrud_invoke}"/>
                            </h:commandLink>
                            <h:outputText value=" "/>
                            <h:commandLink value="Edit" action="#{usuario.editSetup}">
                                <f:param name="jsfcrud.currentUsuario" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][usuario.converter].jsfcrud_invoke}"/>
                            </h:commandLink>
                            <h:outputText value=" "/>
                            <h:commandLink value="Destroy" action="#{usuario.remove}">
                                <f:param name="jsfcrud.currentUsuario" value="#{jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method['getAsConvertedString'][item][usuario.converter].jsfcrud_invoke}"/>
                            </h:commandLink>
                        </h:column>

                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{usuario.createSetup}" value="New Usuario"/>
                <br />
                <br />
                <h:commandLink value="Index" action="welcome" immediate="true" />


            </h:form>
        </body>
    </html>
</f:view>

Project/unops3/web/usuario/New.jsp
<%@page contentType="text/html"%>
<%@page pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsf/core" prefix="f" %>
<%@taglib uri="http://java.sun.com/jsf/html" prefix="h" %>
<f:view>
    <html>
        <head>
            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
            <title>New Usuario</title>
            <link rel="stylesheet" type="text/css" href="/unops3/faces/jsfcrud.css" />
        </head>
        <body>
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h1>New Usuario</h1>
            <h:form>
                <h:inputHidden id="validateCreateField" validator="#{usuario.validateCreate}" value="value"/>
                <h:panelGrid columns="2">
                    <h:outputText value="IdUsuario:"/>
                    <h:inputText id="idUsuario" value="#{usuario.usuario.idUsuario}" title="IdUsuario" required="true" requiredMessage="The idUsuario field is required." />
                    <h:outputText value="NombreUsuario:"/>
                    <h:inputText id="nombreUsuario" value="#{usuario.usuario.nombreUsuario}" title="NombreUsuario" />
                    <h:outputText value="IncidenteCollection:"/>
                    <h:selectManyListbox id="incidenteCollection" value="#{usuario.usuario.jsfcrud_transform[jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method.collectionToArray][jsfcrud_class['unops34.util.JsfUtil'].jsfcrud_method.arrayToList].incidenteCollection}" title="IncidenteCollection" size="6" converter="#{incidente.converter}" >
                        <f:selectItems value="#{incidente.incidenteItemsAvailableSelectMany}"/>
                    </h:selectManyListbox>
                    <h:outputText value="IdPerfil:"/>
                    <h:selectOneMenu id="idPerfil" value="#{usuario.usuario.idPerfil}" title="IdPerfil" required="true" requiredMessage="The idPerfil field is required." >
                        <f:selectItems value="#{perfil.perfilItemsAvailableSelectOne}"/>
                    </h:selectOneMenu>

                </h:panelGrid>
                <br />
                <h:commandLink action="#{usuario.create}" value="Create"/>
                <br />
                <br />
                <h:commandLink action="#{usuario.listSetup}" value="Show All Usuario Items" immediate="true"/>
                <br />
                <br />
                <h:commandLink value="Index" action="welcome" immediate="true" />

            </h:form>
        </body>
    </html>
</f:view>